# Generated by Django 4.1.7 on 2023-04-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EbookApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
    ]
