# Generated by Django 4.1.7 on 2023-04-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EbookApp', '0002_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
